node_id: "kalshi-node-1"
venue: "KALSHI"
environment: "demo"

grpc_listen_addr: ":50053"

kalshi:
  websocket_url: "wss://demo-api.kalshi.co/trade-api/ws/v2"
  venue_market_id: "KXBTCMAX150-25"
  canonical_market_id: "BTC_HIT_150K"
  stale_after_ms: 3000
  api_key_id: "b9157654-b535-4441-8140-43d531427a52"
  private_key_path: "secrets/kalshi_secret_key.pem"

mock_mode: false
